data:
  name: mvtec # mvtect, mvtect loco
  mvtec_data_dir: /home/tienthuan29/workspaces/projects/AiResearch/ImageAnomalyDetection/datasets/mvtec_anomaly_detection
  visa_data_dir:
  category: cable
  mask: True
  # mvtec: ['carpet', 'bottle', 'hazelnut', 'leather', 'cable', 'capsule', 'grid', 'pill', 'transistor', 'metal_nut', 'screw','toothbrush', 'zipper', 'tile', 'wood']
  
general:
  seed: 42
  batch_size: 8
  image_size: 256
  input_channels: 3
  output_channels: 3
  cuda: 0

vae_model:
  name: vae_resnet # vae_resnet, vae_unet
  lr: 3e-4
  epochs: 5000
  weight_decay: 1e-5
  z_dim: 256
  dropout_p: 0.1
  save_freq: 30
  sample_freq: 30
  backbone: resnet18 # resnet18, resnet34, resnet50
  optimizer_name: AdamW # Adam, SGD, AdamW
  train_result_base_dir: ./mvtec_phase1_vae_skip/train_results/
  pretrained_save_base_dir: ./mvtec_phase1_vae_skip/vae_pretrained/
  resume_checkpoint:

diffusion_model:
  name: diffusion_model
  z_dim: 256
  lr: 3e-4
  epochs: 1000
  beta_start: 0.0001
  beta_end: 0.02
  num_timesteps: 1000
  dropout_p: 0.1
  weight_decay: 1e-5
  optimizer_name: AdamW # Adam, SGD, AdamW
  beta_schedule: linear # linear, cosine
  train_result_base_dir: ./mvtec_phase2_diffusion/train_results/
  pretrained_save_base_dir: ./mvtec_phase2_diffusion/diffu_pretrained/
  phase1_vae_pretrained_path: /home/tienthuan29/workspaces/projects/AiResearch/ImageAnomalyDetection/src/main-v1.2/mvtec_phase1_vae/vae_pretrained/vae_resnet/resnet18/bottle/bottle_vae_best.pth
  eval_interval: 10
  reconstruction:
    strength: 0.3
    steps: 70
    eta: 0.0
  resume_training: True
  resume_checkpoint_path:

early_stopping:
  is_early_stopping: True
  patience: 50
  min_delta: 0.01
  smoothing_window: 5

vae_testing:
  name: vae_resnet # vae_resnet, vae_unet
  category: cable
  vae_test_result_base_dir: ./mvtec_phase1_vae_skip/vae_testing/
  vae_model_path: /home/tienthuan29/workspaces/projects/AiResearch/ImageAnomalyDetection/src/main-v1.2/mvtec_phase1_vae_skip/vae_pretrained/vae_resnet/resnet18/cable/cable_vae_best.pth

diffusion_testing:
  category: bottle
  # Image score type name
  image_score_type_name: std # max, mean, std
  diffusion_test_result_base_dir: ./mvtec_phase2_diffusion/diffusion_testing/
  diffusion_model_path: /home/tienthuan29/workspaces/projects/AiResearch/ImageAnomalyDetection/src/main-v1.2/mvtec_phase2_diffusion/diffu_pretrained/bottle/diffusion_model_610_.pth
  diffusion_vae_model_path: /home/tienthuan29/workspaces/projects/AiResearch/ImageAnomalyDetection/src/main-v1.2/mvtec_phase1_vae/vae_pretrained/vae_resnet/resnet18/bottle/bottle_vae_best.pth
  # Visualization settings
  save_visualizations: True
  max_visualization_batches: 5
  max_images_per_batch: 8
