# Example configuration for inference with visualizations
# Copy this to config.yml and update the paths

data:
  name: mvtec
  mvtec_data_dir: /path/to/your/mvtec_dataset
  category: bottle  # Change to your desired category
  mask: True

general:
  seed: 42
  batch_size: 8
  image_size: 256
  input_channels: 3
  output_channels: 3
  cuda: 0

# VAE model configuration (for loading the VAE)
vae_model:
  name: vae_resnet
  z_dim: 256
  dropout_p: 0.1
  backbone: resnet18

# Diffusion model configuration
diffusion_model:
  num_timesteps: 1000
  beta_schedule: linear

# Testing configuration with visualization settings
diffusion_testing:
  category: bottle  # Must match data.category
  diffusion_model_path: /path/to/your/diffusion_model.pth
  diffusion_vae_model_path: /path/to/your/vae_model.pth
  
  # Visualization settings
  save_visualizations: True          # Enable/disable visualizations
  max_visualization_batches: 5       # Number of batches to visualize
  max_images_per_batch: 8           # Max images per batch to save

# Other configurations...
vae_model:
  name: vae_resnet
  lr: 1e-4
  epochs: 5000
  weight_decay: 1e-5
  z_dim: 256
  dropout_p: 0.1
  save_freq: 30
  sample_freq: 30
  backbone: resnet18
  optimizer_name: AdamW
  train_result_base_dir: ./mvtec_phase1_vae/train_results/
  pretrained_save_base_dir: ./mvtec_phase1_vae/vae_pretrained/

early_stopping:
  is_early_stopping: True
  patience: 100
  min_delta: 0.01
  smoothing_window: 5 